### ISSUE TITLE
Enumerations are not generated

### ISSUE THREAD

**Issue by darrenhull** [lstrzepek/DomainModel.Generator#7]
when generating class diagrams Enum properties are not generated:

![image](https://user-images.githubusercontent.com/825654/211600231-4195d3e8-904b-4cef-a787-188793792f14.png)

![image](https://user-images.githubusercontent.com/825654/211600437-e47d520d-8732-45fb-91d3-c3cdb747cdb1.png)

![image](https://user-images.githubusercontent.com/825654/211600678-5812c6ee-029b-4010-8164-f8bffd87f341.png)

**Comment by lstrzepek** [comment]
Hi! Can you propose how this enum should look like on Class diagram to not mislead that this is a regular class? I think in uml it is done by attribute or something. But some example would be appreciated.

**Comment by lstrzepek** [comment]
By the way thanks for the first issue 🙃

**Comment by lstrzepek** [comment]
I think it can look something like this:
![enums](https://user-images.githubusercontent.com/185352/211650050-724b4e43-8435-4015-b936-4d32824cb606.svg)

**Comment by darrenhull** [comment]
Yes i think that would be good although in Class diagrams the <<enumeration>> is below the name. This is as close as I have got without adding any styling:
![image](https://user-images.githubusercontent.com/825654/211770887-33cd95ed-65f3-4130-b6a0-8a0379285cb2.png)

**Comment by lstrzepek** [comment]
I couldn't find any information about placing stereotypes below the class name. On all diagrams I found it is above. So I stayed with common mermaid approach. Hope it will work for you.

**Comment by darrenhull** [comment]
Hi, this is working as expected now:

![image](https://user-images.githubusercontent.com/825654/213236487-aba7a713-39dd-48d0-8f62-e4914283f28a.png)

Thanks. Although for an enum i'm not sure if it should have the +
